[app]
name = "im"
env = "local"
http_addr = ":9091"

[server]
tcp_addr = ":50055"
udp_addr = ":50055"

[log]
tag = "local"
addr = "192.168.97.55:6208"
level = -1 # -1 DEBUG 0 INFO

[keys]
tcp0x888 = "tcp0x888"
udp0x10e = "udp0x10e"
udp0x10f = "udp0x10f"
